# Generated by Django 3.0.4 on 2020-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='frequency',
            field=models.CharField(choices=[('', 'Select Payment Frequency Type'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('biannual', 'Biannual'), ('yearly', 'Yearly')], default='', max_length=29),
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('', 'Select Membership Type'), ('unlimited', 'Unlimited'), ('barbell club', 'Barbell Club'), ('crossfit', 'Crossfit')], max_length=22),
        ),
    ]
