# Generated by Django 3.0.4 on 2020-04-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200424_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='frequency',
            field=models.CharField(choices=[('', 'Select Payment Frequency Type'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('biannual', 'Biannual'), ('yearly', 'Yearly')], max_length=29),
        ),
    ]
