# Generated by Django 3.0.4 on 2020-03-14 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.CharField(choices=[('', ''), ('crossfit', 'Crossfit'), ('olympic weightlifting', 'Olympic Weightlifting'), ('powerlifting', 'Powerlifting'), ('general', 'General'), ('physiotherapy', 'physiotherapy'), ('health', 'Health'), ('nutrition', 'Nutrition'), ('gymnastics', 'Gymnastics'), ('personal training', 'Personal Training')], max_length=21)),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
