# Generated by Django 3.0.4 on 2020-04-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('', 'Select Post Category'), ('crossfit', 'Crossfit'), ('olympic weightlifting', 'Olympic Weightlifting'), ('powerlifting', 'Powerlifting'), ('general', 'General'), ('physiotherapy', 'Physiotherapy'), ('health', 'Health'), ('nutrition', 'Nutrition'), ('gymnastics', 'Gymnastics'), ('personal training', 'Personal Training')], max_length=21),
        ),
    ]
