# Generated by Django 3.0.4 on 2020-04-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200410_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='post_body',
        ),
    ]
