# Generated by Django 3.0.4 on 2020-04-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200410_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_body',
            new_name='post_text',
        ),
    ]
