# Generated by Django 3.0.4 on 2020-04-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
