# Generated by Django 3.0.4 on 2020-04-28 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_title', models.CharField(max_length=150)),
                ('query_text', models.TextField()),
                ('query_email', models.EmailField(max_length=254)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('query_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
