# Generated by Django 3.0.4 on 2020-03-22 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='default.jpg', upload_to='img/%Y/%m/%d/')),
                ('brief_desc', models.CharField(max_length=300)),
                ('qualification_1', models.CharField(choices=[('', ''), ('cf lvl1 trainer', 'CF Lvl1 Trainer'), ('strength & conditioning specialist (cscs)', 'Strength & Conditioning Specialist (cscs)'), ('precision nutrition lvl1 certificate', 'Precision Nutrition Lvl1 Certificate'), ('neuromuscular therapist', 'Neuromuscular Therapist'), ('weightlifting lvl1', 'Weightlifting Lvl1'), ('exercise & fitness from ul', 'Exercise & Fitness from UL'), ('bsc in strength & conditioning', 'BSc in Strength & Conditioning')], max_length=41)),
                ('qualification_2', models.CharField(choices=[('', ''), ('cf lvl1 trainer', 'CF Lvl1 Trainer'), ('strength & conditioning specialist (cscs)', 'Strength & Conditioning Specialist (cscs)'), ('precision nutrition lvl1 certificate', 'Precision Nutrition Lvl1 Certificate'), ('neuromuscular therapist', 'Neuromuscular Therapist'), ('weightlifting lvl1', 'Weightlifting Lvl1'), ('exercise & fitness from ul', 'Exercise & Fitness from UL'), ('bsc in strength & conditioning', 'BSc in Strength & Conditioning')], max_length=41)),
                ('qualification_3', models.CharField(choices=[('', ''), ('cf lvl1 trainer', 'CF Lvl1 Trainer'), ('strength & conditioning specialist (cscs)', 'Strength & Conditioning Specialist (cscs)'), ('precision nutrition lvl1 certificate', 'Precision Nutrition Lvl1 Certificate'), ('neuromuscular therapist', 'Neuromuscular Therapist'), ('weightlifting lvl1', 'Weightlifting Lvl1'), ('exercise & fitness from ul', 'Exercise & Fitness from UL'), ('bsc in strength & conditioning', 'BSc in Strength & Conditioning')], max_length=41)),
                ('qualification_4', models.CharField(choices=[('', ''), ('cf lvl1 trainer', 'CF Lvl1 Trainer'), ('strength & conditioning specialist (cscs)', 'Strength & Conditioning Specialist (cscs)'), ('precision nutrition lvl1 certificate', 'Precision Nutrition Lvl1 Certificate'), ('neuromuscular therapist', 'Neuromuscular Therapist'), ('weightlifting lvl1', 'Weightlifting Lvl1'), ('exercise & fitness from ul', 'Exercise & Fitness from UL'), ('bsc in strength & conditioning', 'BSc in Strength & Conditioning')], max_length=41)),
                ('currently_active', models.BooleanField(default=True)),
                ('employed_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
