# Generated by Django 3.0.4 on 2020-03-22 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='StaffMember',
        ),
    ]
