# Generated by Django 3.0.4 on 2020-03-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_auto_20200322_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='qualification_1',
            field=models.CharField(blank=True, choices=[('', ''), ('cf lvl1 trainer', 'CF Lvl1 Trainer'), ('strength & conditioning specialist (cscs)', 'Strength & Conditioning Specialist (cscs)'), ('precision nutrition lvl1 certificate', 'Precision Nutrition Lvl1 Certificate'), ('neuromuscular therapist', 'Neuromuscular Therapist'), ('weightlifting lvl1', 'Weightlifting Lvl1'), ('exercise & fitness from ul', 'Exercise & Fitness from UL'), ('bsc in strength & conditioning', 'BSc in Strength & Conditioning')], max_length=41),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='qualification_2',
            field=models.CharField(blank=True, choices=[('', ''), ('cf lvl1 trainer', 'CF Lvl1 Trainer'), ('strength & conditioning specialist (cscs)', 'Strength & Conditioning Specialist (cscs)'), ('precision nutrition lvl1 certificate', 'Precision Nutrition Lvl1 Certificate'), ('neuromuscular therapist', 'Neuromuscular Therapist'), ('weightlifting lvl1', 'Weightlifting Lvl1'), ('exercise & fitness from ul', 'Exercise & Fitness from UL'), ('bsc in strength & conditioning', 'BSc in Strength & Conditioning')], max_length=41),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='qualification_3',
            field=models.CharField(blank=True, choices=[('', ''), ('cf lvl1 trainer', 'CF Lvl1 Trainer'), ('strength & conditioning specialist (cscs)', 'Strength & Conditioning Specialist (cscs)'), ('precision nutrition lvl1 certificate', 'Precision Nutrition Lvl1 Certificate'), ('neuromuscular therapist', 'Neuromuscular Therapist'), ('weightlifting lvl1', 'Weightlifting Lvl1'), ('exercise & fitness from ul', 'Exercise & Fitness from UL'), ('bsc in strength & conditioning', 'BSc in Strength & Conditioning')], max_length=41),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='qualification_4',
            field=models.CharField(blank=True, choices=[('', ''), ('cf lvl1 trainer', 'CF Lvl1 Trainer'), ('strength & conditioning specialist (cscs)', 'Strength & Conditioning Specialist (cscs)'), ('precision nutrition lvl1 certificate', 'Precision Nutrition Lvl1 Certificate'), ('neuromuscular therapist', 'Neuromuscular Therapist'), ('weightlifting lvl1', 'Weightlifting Lvl1'), ('exercise & fitness from ul', 'Exercise & Fitness from UL'), ('bsc in strength & conditioning', 'BSc in Strength & Conditioning')], max_length=41),
        ),
    ]
