# Generated by Django 3.0.4 on 2020-03-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_auto_20200322_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='media/%Y/%m/%d/'),
        ),
    ]
