# Generated by Django 3.0.4 on 2020-03-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0005_auto_20200323_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='currently_active',
            new_name='currently_employed',
        ),
    ]
