# Generated by Django 3.0.4 on 2020-03-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_auto_20200323_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='photo',
            field=models.URLField(default='https://static.thenounproject.com/png/363639-200.png'),
        ),
    ]
