# Generated by Django 3.0.4 on 2020-03-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0007_auto_20200329_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='photo',
            new_name='photo_url',
        ),
    ]
